Repository sopt-makers/sopt.org-backend-spring, pull requests merged in 2025-01, with the labels that each got.

#17 [Feat]:sopticle, visitor 조회 기능 v2 API 마이그레이션 작업
  Dockerfile
  build.gradle
  src/main/java/sopt/org/homepage/HomepageApplication.java
  src/main/java/sopt/org/homepage/aboutsopt/AboutSoptService.java
  src/main/java/sopt/org/homepage/aboutsopt/entity/CoreValueEntity.java
  src/main/java/sopt/org/homepage/common/constants/CacheType.java
  src/main/java/sopt/org/homepage/config/AuthConfig.java
  src/main/java/sopt/org/homepage/config/CacheConfig.java
  src/main/java/sopt/org/homepage/entity/SopticleAuthorEntity.java
  src/main/java/sopt/org/homepage/entity/SopticleEntity.java
  src/main/java/sopt/org/homepage/entity/SopticleLikeEntity.java
  src/main/java/sopt/org/homepage/internal/crew/CrewClient.java
  src/main/java/sopt/org/homepage/internal/crew/CrewService.java
  src/main/java/sopt/org/homepage/main/service/MainService.java
  src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/SopticleController.java
  src/main/java/sopt/org/homepage/sopticle/SopticleService.java
  src/main/java/sopt/org/homepage/sopticle/dto/request/CreateSopticleAuthorDto.java
  src/main/java/sopt/org/homepage/sopticle/dto/request/CreateSopticleAuthorRole.java
  src/main/java/sopt/org/homepage/sopticle/dto/request/CreateSopticleDto.java
  src/main/java/sopt/org/homepage/sopticle/dto/request/GetSopticleListRequestDto.java
  src/main/java/sopt/org/homepage/sopticle/dto/response/CreateSopticleResponseDto.java
  src/main/java/sopt/org/homepage/sopticle/dto/response/LikeSopticleResponseDto.java
  src/main/java/sopt/org/homepage/sopticle/dto/response/SopticleResponseDto.java
  src/main/java/sopt/org/homepage/sopticle/entity/SopticleAuthorEntity.java
  src/main/java/sopt/org/homepage/sopticle/entity/SopticleEntity.java
  src/main/java/sopt/org/homepage/sopticle/entity/SopticleLikeEntity.java
  src/main/java/sopt/org/homepage/sopticle/repository/SopticleAuthorRepository.java
  src/main/java/sopt/org/homepage/sopticle/repository/SopticleLikeRepository.java
  src/main/java/sopt/org/homepage/sopticle/repository/SopticleQueryRepository.java
  src/main/java/sopt/org/homepage/sopticle/repository/SopticleRepository.java
  src/main/java/sopt/org/homepage/sopticle/scrap/ScraperService.java
  src/main/java/sopt/org/homepage/sopticle/scrap/dto/CreateScraperResponseDto.java
  src/main/java/sopt/org/homepage/sopticle/scrap/dto/ScrapArticleDto.java
  src/main/java/sopt/org/homepage/visitor/VisitorController.java
  src/main/java/sopt/org/homepage/visitor/VisitorService.java
  src/main/java/sopt/org/homepage/visitor/dto/GetTodayVisitorResponseDto.java
  src/main/java/sopt/org/homepage/visitor/dto/VisitorCountUpResponseDto.java
Labels: size/XXL

#18 [Refac]: 어드민 프론트 QA 요청사항 반영
  src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
  src/main/java/sopt/org/homepage/main/dto/response/GetAboutPageResponseDto.java
  src/main/java/sopt/org/homepage/main/dto/response/GetMainPageResponseDto.java
  src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
Labels: size/M

#19 [Fix]: AboutSoptService MainService 순환참조 오류 수정 & Crew API Token 환경 변수 추가
  src/main/java/sopt/org/homepage/aboutsopt/AboutSoptService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🐞Fix, size/XS

#21 Feat/#20 interface separation
  src/main/java/sopt/org/homepage/aboutsopt/AboutSoptController.java
  src/main/java/sopt/org/homepage/aboutsopt/service/AboutSoptService.java
  src/main/java/sopt/org/homepage/aboutsopt/service/AboutSoptServiceImpl.java
  src/main/java/sopt/org/homepage/common/service/GenerationService.java
  src/main/java/sopt/org/homepage/internal/playground/PlaygroundService.java
  src/main/java/sopt/org/homepage/internal/playground/PlaygroundServiceImpl.java
  src/main/java/sopt/org/homepage/main/service/MainService.java
  src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
  src/main/java/sopt/org/homepage/project/ProjectController.java
  src/main/java/sopt/org/homepage/project/service/ProjectService.java
  src/main/java/sopt/org/homepage/project/service/ProjectServiceImpl.java
  src/main/java/sopt/org/homepage/review/ReviewController.java
  src/main/java/sopt/org/homepage/review/service/ReviewService.java
  src/main/java/sopt/org/homepage/review/service/ReviewServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/SopticleController.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperService.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/service/SopticleService.java
  src/main/java/sopt/org/homepage/sopticle/service/SopticleServiceImpl.java
  src/main/java/sopt/org/homepage/visitor/VisitorController.java
  src/main/java/sopt/org/homepage/visitor/service/VisitorService.java
  src/main/java/sopt/org/homepage/visitor/service/VisitorServiceImpl.java
Labels: 🔨Refactor, size/XL

#22 fix: S3 FileKey 파싱 오류 수정 & CrewService 이전기수 하드코딩 현재 구조로 수정
  src/main/java/sopt/org/homepage/aboutsopt/service/AboutSoptService.java
  src/main/java/sopt/org/homepage/aboutsopt/service/AboutSoptServiceImpl.java
  src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
  src/main/java/sopt/org/homepage/internal/crew/CrewService.java
  src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
Labels: 🐞Fix, size/M

#24 [Feat]: 공홈 V2 서버 프로덕션 배포 작업
  .github/workflows/cd.production.yml
Labels: 🌍Deploy, size/M

#26 feat: v2 서버 최종 QA 및 프로덕션 배포
  .github/workflows/cd.develop.yml
  .github/workflows/cd.production.yml
  src/main/java/sopt/org/homepage/notification/NotificationController.java
  src/main/java/sopt/org/homepage/notification/NotificationService.java
Labels: size/L

#27 [Fix]: S3 FileKey 기반으로 이미지링크 저장시, SignedLink 대신 원본 URL 로 저장되도록 수정
  src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
Labels: size/L

#28 [Fix]: S3 FileKey 기반으로 이미지링크 저장시, SignedLink 대신 원본 URL 로 저장되도록 수정
  src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
Labels: size/L
