Repository sopt-makers/sopt.org-backend-spring, pull requests merged in 2025-03, with the labels that each got.

#31 Feat/#30 replace sutdy api
  src/main/java/sopt/org/homepage/aboutsopt/service/AboutSoptServiceImpl.java
  src/main/java/sopt/org/homepage/common/mapper/ResponseMapper.java
  src/main/java/sopt/org/homepage/internal/crew/CrewClient.java
  src/main/java/sopt/org/homepage/internal/crew/CrewService.java
  src/main/java/sopt/org/homepage/internal/crew/dto/AppliedInfo.java
  src/main/java/sopt/org/homepage/internal/crew/dto/CrewMeetingList.java
  src/main/java/sopt/org/homepage/internal/crew/dto/CrewMeetingResponse.java
  src/main/java/sopt/org/homepage/internal/crew/dto/CrewMeetingVo.java
  src/main/java/sopt/org/homepage/internal/crew/dto/ImageURL.java
  src/main/java/sopt/org/homepage/internal/crew/dto/MeetingJoinablePart.java
  src/main/java/sopt/org/homepage/internal/crew/dto/PaginationMeta.java
  src/main/java/sopt/org/homepage/internal/crew/dto/StudyCountResponse.java
  src/main/java/sopt/org/homepage/internal/crew/dto/StudyResponse.java
  src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
Labels: 🔨Refactor, size/L

#32 deploy : 통합 dev 인스턴스 이전으로 인한 포트 변경
  .github/workflows/cd.develop.yml
Labels: size/XS

#33 deploy : aws username 수정
  .github/workflows/cd.develop.yml
Labels: size/XS

#34 deploy : key이름 변경
  .github/workflows/cd.develop.yml
Labels: size/XS

#35 deploy : DEV 통합 인스턴스에 맞는 디렉토리 구조로 script 수정
  .github/workflows/cd.develop.yml
Labels: size/XS

#38 [Refac] 솝티클 스크래핑 기능 개선
  Dockerfile
  src/main/java/sopt/org/homepage/sopticle/scrap/CrawlerComposite.java
  src/main/java/sopt/org/homepage/sopticle/scrap/LinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/LinkSource.java
  src/main/java/sopt/org/homepage/sopticle/scrap/WebDriverManager.java
  src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BasicLinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BehanceLinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BrunchLinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/crawler/NaverLinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/crawler/VelogMainLinkCrawler.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperServiceImpl.java
Labels: size/XL

#40 [Feat] 활동후기 추가 API 작업
  src/main/java/sopt/org/homepage/review/ReviewController.java
  src/main/java/sopt/org/homepage/review/dto/request/AddReviewRequestDto.java
  src/main/java/sopt/org/homepage/review/entity/ReviewEntity.java
  src/main/java/sopt/org/homepage/review/repository/ReviewRepository.java
  src/main/java/sopt/org/homepage/review/service/ReviewService.java
  src/main/java/sopt/org/homepage/review/service/ReviewServiceImpl.java
  src/main/java/sopt/org/homepage/scrap/CrawlerComposite.java
  src/main/java/sopt/org/homepage/scrap/LinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/LinkSource.java
  src/main/java/sopt/org/homepage/scrap/WebDriverManager.java
  src/main/java/sopt/org/homepage/scrap/crawler/BasicLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/BehanceLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/BrunchLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/NaverLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/VelogMainLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/dto/CreateScraperResponseDto.java
  src/main/java/sopt/org/homepage/scrap/dto/ScrapArticleDto.java
  src/main/java/sopt/org/homepage/scrap/service/ScraperService.java
  src/main/java/sopt/org/homepage/scrap/service/ScraperServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperService.java
  src/main/java/sopt/org/homepage/sopticle/service/SopticleServiceImpl.java
Labels: ✨Feature, size/XL

#41 [Fix] 스크래핑 오류 수정
  build.gradle
  src/main/java/sopt/org/homepage/scrap/WebDriverManager.java
  src/main/java/sopt/org/homepage/scrap/crawler/BasicLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/BrunchLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/NaverLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/VelogMainLinkCrawler.java
Labels: size/L

#42 [Feat] 웹 크롤링 기능 개선 & 활동후기 추가 API
  Dockerfile
  build.gradle
  src/main/java/sopt/org/homepage/review/ReviewController.java
  src/main/java/sopt/org/homepage/review/dto/request/AddReviewRequestDto.java
  src/main/java/sopt/org/homepage/review/entity/ReviewEntity.java
  src/main/java/sopt/org/homepage/review/repository/ReviewRepository.java
  src/main/java/sopt/org/homepage/review/service/ReviewService.java
  src/main/java/sopt/org/homepage/review/service/ReviewServiceImpl.java
  src/main/java/sopt/org/homepage/scrap/CrawlerComposite.java
  src/main/java/sopt/org/homepage/scrap/LinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/LinkSource.java
  src/main/java/sopt/org/homepage/scrap/WebDriverManager.java
  src/main/java/sopt/org/homepage/scrap/crawler/BasicLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/BehanceLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/BrunchLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/NaverLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/crawler/VelogMainLinkCrawler.java
  src/main/java/sopt/org/homepage/scrap/dto/CreateScraperResponseDto.java
  src/main/java/sopt/org/homepage/scrap/dto/ScrapArticleDto.java
  src/main/java/sopt/org/homepage/scrap/service/ScraperService.java
  src/main/java/sopt/org/homepage/scrap/service/ScraperServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperService.java
  src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperServiceImpl.java
  src/main/java/sopt/org/homepage/sopticle/service/SopticleServiceImpl.java
Labels: size/XXL

#44 [CHORE] Issue 및 Pr 템플릿 수정
  .github/ISSUE_TEMPLATE/issue-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, 📝 chore
